### ISSUE TITLE
Does it work with PHP built in server?

### ISSUE THREAD

**Issue by ghost** [RWOverdijk/AssetManager#139]
After the "get started tutorial", everything works fine with apache2. If I try to run the same example with php -S 0.0.0.0 5000 -t public a 404 response is served.

**Comment by vrkansagara** [comment]
@Ocramius  This issue still persist.

**Comment by Ocramius** [comment]
@vrkansagara send a patch - nobody actively working on this, unless you contribute yourself.

**Comment by vrkansagara** [comment]
@Ocramius  I really like this package and definitely going to contribute. Can I ask favor for the already requested PR to be processed !

**Comment by Ocramius** [comment]
You'll need @RWOverdijk for that 😁

**Comment by RWOverdijk** [comment]
Yo @Ocramius this repo is up for grabs. Fork it, slap it, call it daddy. 

I should probably archive it, but I'm not sure if that'll affect current dependents or not which is why I haven't done it yet.

**Comment by Ocramius** [comment]
Archiving is fine too, if no maintenance is expected: I have too much
workload to pick this one up too.

**Comment by vrkansagara** [comment]
> I usually work with the internal PHP server locally, and had no problem with `AssetManager` so far.

@Ocramius Would you like to share how you start php built in web server. I mean what command you execute from which directory. 
As I tried my past command which is not working with fresh skeleton application so
> sudo -u www-data php -S 0.0.0.0:8090 -t public/
