### ISSUE TITLE
Upgrade Assetic to 1.2.1

### ISSUE THREAD

**Issue by solcre** [RWOverdijk/AssetManager#161]
Hey Wesley I just upgraded Assetic to 1.2.1 and all tests are passing. I found out a problem with StringAsset and I looked in the Assetic Repo and it was already fixed, that's why I tried to upgrade and all tests are passing.

What do you say?

**Comment by RWOverdijk** [comment]
@solcre I'd say, if it works, you're welcome to submit a PR! :)

**Comment by solcre** [comment]
Doing it soon, and I will add a Failing Test case for a specific scenario (not related to Assetic version) but to filter aplying logic.

The scenario is:

Filters by extension or by mime type gets applied twice for AssetCollection. 

I'm submitting a fix proposal in a separate PR so we can first merge the Assetic version Update.

Catcha on freenode (nickname: xxMatiasxx in #apigility or #zftalk)

**Comment by elchristo** [comment]
@RWOverdijk I think this issue is outdated and can be closed as you just upgraded to Assetic 1.4 with #213
