### ISSUE TITLE
1.4.2 - ResolverInterface BC Break?

### ISSUE THREAD

**Issue by mtudor** [RWOverdijk/AssetManager#167]
Hi guys,

Just a quick heads-up that 1.4.2 broke my application because of the change to the ResolverInterface - the addition of a collect() method caused a fatal error (implement or declare abstract) because I had not implemented this function in my resolvers.

Not too difficult to fix but do you think this should have been a major version bump?

Mark.

**Comment by mtudor** [comment]
Ah, and I've just noticed that @sokac had mentioned the BC break in the PR (#138).  ;-)

**Comment by RWOverdijk** [comment]
@mtudor You're right. A mess up on my side; I should've changed the version number. Unfortunately nothing I can do about it now.

**Comment by Ocramius** [comment]
It has to be reverted for 1.4.3, then you release 2.0.0

**Comment by mtudor** [comment]
@RWOverdijk Easily done and no worries.  I was wondering whether there was anything we could do about it and the options I came up with were:
 - 1. Revert the change to the interface and tag 1.4.3, then reintroduce the change and tag 2.0.0.
 - 2. Risk annoying people (!) and remove 1.4.3 and re-tag 2.0.0.
 - 3. Meh, never mind, do nothing ;-)

Option 1 is the nicest to people who indiscriminately do "composer update" and assume all will be fine, option 3 is the easiest! ;-)

**Comment by RWOverdijk** [comment]
@Ocramius That's what I was going to do. But I can't fix 1.4.2 anymore.

**Comment by mtudor** [comment]
@Ocramius @RWOverdijk Ok, you guys are ahead of me ;-)

**Comment by Ocramius** [comment]
@RWOverdijk you'd have to fix it for 1.4.3.

**Comment by RWOverdijk** [comment]
@Ocramius That's what I just said haha
