### ISSUE TITLE
Can you add a changelog file ?

### ISSUE THREAD

**Issue by bfolliot** [RWOverdijk/AssetManager#172]
Hello.
Can you add a changelog file?

For example, i use the 1.3.7 version and i don't know if you have introduct backwards compatibility breaks and new features.

**Comment by RWOverdijk** [comment]
@bfolliot We follow semver. There are no BC breaks as it stands. If you wish to see what changed you can take a look at the history.

1.4.x introduced some features, but didn't break BC.
