### ISSUE TITLE
[Question] Accessing to asset fire dispatch.error event ???

### ISSUE THREAD

**Issue by mmgajic** [RWOverdijk/AssetManager#174]
Hi, thanks for your time in advance!!!

I noticed that everytime when I try to access to some asset (any js or css file) with for example: /public/example.js path,  dispatch.error event has been triggered. Is that regular, and how I can escape that?

That is because there is no route for such request and I'm getting error logged everytime. Because I'm listening that event and log.

**Comment by Ocramius** [comment]
Yes, this is normal. AssetManager acts before a 404 is being sent out.

**Comment by mmgajic** [comment]
Thanks for your response. I will than check if path is /public, and than just exit from my error handler.

Cheers!
