### ISSUE TITLE
How to refresh browser cache after Deployment?

### ISSUE THREAD

**Issue by makseo** [RWOverdijk/AssetManager#177]
Sorry, but I can not understand, how can I update a browser cache after changes?
Is it possible at all in AssetManager?
I know two possibilities.
1. To set header Cache-control & Expires.
2. Or append some unique string to assets, ex. /assets/css/main.css?123
Also I have an idea, to append a last modified date, which I can get from asset file automatically and convert it to timestamp, ex. /assets/css/main.css?1231434698590
Can you help me please? Thx

**Comment by RWOverdijk** [comment]
Hey @makseo,

Usually, browser cache is handled by the file server. Those headers are sent along by apache, nginx etc. You could have the browser revalidate the assets, or like you said add a string to the asset. A cache busting implementation which caches the results would be ideal here (e.g. a cached array of asset => hash). I'd love a PR for this.

**Comment by pensiero** [comment]
@RWOverdijk I was just thinking to do a PR to solve this problem. I spoke with @Ocramius and he agrees.

I just need some indications to create this implementation. I was thinking to create a ViewHelper named `AssetManagerTimestamp` that simply show the unix_timestamp of the file passed to him as parameter.

Do you think it will be fine? If so, do you think I need to attach a cache system? I think that the only method that I will call is `filemtime`.

**Comment by RWOverdijk** [comment]
@pensiero You could take a look at http://symfony.com/doc/current/cookbook/assetic/asset_management.html

**Comment by pensiero** [comment]
I was just thinking this morning to do something similar.. basically it's a view helper the print the entire path, not only the unix_timestamp param. Nice, I can do it.
