### ISSUE TITLE
ServiceLocatorAwareInterface is deprecated and will be removed in version 3.0

### ISSUE THREAD

**Issue by mpozzo** [RWOverdijk/AssetManager#185]
I have this error :

Deprecated: ServiceLocatorAwareInterface is deprecated and will be removed in version 3.0, along with the ServiceLocatorAwareInitializer. Please update your class AssetManager\Service\AssetFilterManager to remove the implementation, and start injecting your dependencies via factory instead.

Can you fix?

**Comment by RWOverdijk** [comment]
@mpozzo A bit busy atm. PRs are more than welcome! :)

**Comment by h3christophe** [comment]
This is a really easy fix 
In the class AssetManager\Service\AssetFilterManager

Just replace  
``
use Zend\ServiceManager\ServiceLocatorAwareInterface;
class AssetFilterManager implements ServiceLocatorAwareInterface, MimeResolverAwareInterface
``
by   
 ``
class AssetFilterManager implements MimeResolverAwareInterface
``


This is the only thing you need to do as the Factory is already injecting the service locator 

Thank you !

**Comment by h3christophe** [comment]
@RWOverdijk  Thank you for your prompt response in this matter

**Comment by RWOverdijk** [comment]
And thank you for the help on this!
