### ISSUE TITLE
Support for EventManager & ServiceManager 3.0

### ISSUE THREAD

**Issue by shandyDev** [RWOverdijk/AssetManager#188]
http://zendframework.github.io/zend-servicemanager/migration/
http://zend-eventmanager.readthedocs.org/en/latest/migration/intro/
I think this will take maximum minor BC. 
Need investigate allowing ZF3 component in composer.json

**Comment by RWOverdijk** [comment]
Thanks for bringing this to our attention.

**Comment by wshafer** [comment]
@RWOverdijk - I was about to refactor this for Expressive, would it make sense to get away from Zend Route / ServiceManager / ModuleManager / MVC etc and move to the PSR7 middleware and container-interop?

If so this would allow me to include both configs for ZF and Expressive.

If you're ok with this shift, I'm happy to do the work.  I have become too accustom to having this package for plugin assets, now that I'm making the switch to Expressive, I miss this package the most. ;)

**Comment by wshafer** [comment]
@RWOverdijk - I just saw the conversation on https://github.com/RWOverdijk/AssetManager/pull/193/files.  Scratch all this.  But ping me if/when we get a ZF3 branch and I can assist with the migration.

**Comment by RWOverdijk** [comment]
@wshafer Will do :)

**Comment by wshafer** [comment]
@RWOverdijk - I believe this issue can be closed per https://github.com/RWOverdijk/AssetManager/pull/193/files being merged.

**Comment by RWOverdijk** [comment]
Happiness. Good start of the day!
