### ISSUE TITLE
Append last modified date to Asset View Helper even withoud cache

### ISSUE THREAD

**Issue by pensiero** [RWOverdijk/AssetManager#189]
Actually the view helper [check that the cache is enabled](https://github.com/RWOverdijk/AssetManager/blob/master/src/AssetManager/View/Helper/Asset.php#L62-L64) and in case [append the last modified date](https://github.com/RWOverdijk/AssetManager/blob/master/src/AssetManager/View/Helper/Asset.php#L73) as query param to the filepath of the asset.

In development environment the cache is off, so the query param is not appended and the browser cache it. 

What about appending the last modified query param every time?

Thanks

**Comment by RWOverdijk** [comment]
@pensiero Good one. But then it always goes to the file, so it doesn't get cached in the browser anyway, right? Or am I missing something?

**Comment by pensiero** [comment]
Well, if the cache is not enabled, the file is re-generated each time the AssetManager View Helper is invoked, so the last modified date is basically the current timestamp.

Is something like forcing the browser to always purge the cache of all the assets of the website. For development purpose I think it could be good, what do you think about?

**Comment by RWOverdijk** [comment]
I think that could be good, but also slow down the dev process. Perhaps make that configurable?

**Comment by pensiero** [comment]
Yes, good idea, I can do it

**Comment by pensiero** [comment]
#190
