### ISSUE TITLE
Asset not loaded on latest ZendSkeletonFramework

### ISSUE THREAD

**Issue by wiryonolau** [RWOverdijk/AssetManager#201]
Hi this is my asset manager config inside module/Application/config/module.config.php

`'asset_manager' => [
	'resolver_configs' => [
		'paths' => [
			__DIR__ . '/../asset'
		]
	],
]`

Then I put all js and css from public folder to module/Application/asset

When loading page all css/js request got 404

**Comment by Ocramius** [comment]
Was this supposed to be closed? What's the resolution?

**Comment by wiryonolau** [comment]
I have my own dispatch error event that stop propogation and give a nice
404 on json format or normal html.

I set my listener priority to be lower then your library but it doesn't
work. Your lib is use -9999999 correct ?

Currently I have too check if the requested uri is  asking for folder
inside asset directory. If it is then pass to your lib. This way it works
for both listener
