### ISSUE TITLE
Create Seperate "Core" repository and package

### ISSUE THREAD

**Issue by wshafer** [RWOverdijk/AssetManager#205]
Would love to decouple this from zendframework/zend-http and instead move to PSR-7 requests/responses so it can also be beneficial to other frameworks like Expressive, Slim, etc in addition to ZF.   Best solution I believe is to move the core files to it's own repository and composer package, that each framework wrapper can include.

Creating this issue based on our discussion in PR #196.

**Comment by wshafer** [comment]
Pieced together what I'm envisioning this split would look like and placing here for comments/suggestions/criticisms.

Main Zend Framework Packages:
[RWOverdijk/AssetManager-Core](https://github.com/wshafer/assetmanager-core)
[RWOverdijk/AssetManager Version 2](https://github.com/wshafer/assetmanager-zf)

I have created a pre-configured sandbox [here](https://github.com/wshafer/assetmanager-zf-test), for playing around with the different features in the Asset Manager and to validate everything is working as expected.  Please feel free to take it out for a spin.

Note:
In addition to adding PSR-7 I have also updated to PSR-4, updated PHPUnit to 5.7 (last version to support 5.6 which is ZF current supported PHP version), updated Assetic to latest version, and updated PHPCS to latest release.

**Comment by RWOverdijk** [comment]
@wshafer I'd like to start off by saying thank you for all your efforts. It's appreciated! :)

I was thinking of moving the repositories to the org (spoonx). It's where everything is. This might be a good time to do that.

I'll take a look at this soon, I'm currently in the middle of something. Maybe @Ocramius also wants to take a look.

**Comment by Ocramius** [comment]
I'm unable to follow along with these changes ATM, but feel free to move the repos as long as you don't break download/clone links.

**Comment by wshafer** [comment]
Yea @Ocramius There's a lot of changes here.  Since I was in these files anyway I decided to update other things.  It was kind of a downward spiral.  Let me see I can document what's changed a bit better.

* The files are built on top of [PR #204](https://github.com/RWOverdijk/AssetManager/pull/204)
* From here we add PSR-7 support to the AssetManager's base class and use the PSR7 bridge in the module.php to pass the correct objects into the AssetManager.
* Next we update the tests to PHPUnit 5.7 since we have to update the tests for PSR-11 and PSR-7 anyway.
* Move all the file now not coupled directly to Zend Framework to a core repository and update the namespace. (This give us a BC break and will require an update to the README.md and the wiki to reflect these changes)
* Since we're moving the files, update the packages to use PSR-4 and delete the src directory.
* Update the base AssetManager repository to consume the lib files from the new namespace.
* Abstract the configuration, based on the previous conversation on [PR #196](https://github.com/RWOverdijk/AssetManager/pull/196)
* Create a new Repo to house the http-interop middleware and Expressive configuration.

Other BC breaks just because are the removal of the Service Manager alias's.  These are not supported in other containers, plus this is clearly a new release so let's remove these while we can.  It will need to be documented in a migration guide, or wiki, or something.

Hope that helps a bit.

**Comment by wshafer** [comment]
@RWOverdijk - Just wanted to check in with ya and see if you'd had any thoughts on how you'd like to proceed.  Would be nice to know your thoughts on breaking this up into a couple of packages for reuse.

Thanks in advance,
Westin

**Comment by RWOverdijk** [comment]
@wshafer I'm being an irresponsible repository owner. My apologies. I was busy with other things and just completely forgot about this.

Are you available on [Gitter](https://gitter.im/) by any chance? I have some ideas to run by you regarding this approach. I think it'll be settled a lot quicker that way.

**Comment by wshafer** [comment]
V2 Core Dev Branch now located here: https://github.com/wshafer/assetmanager-core

Final V2 Core Dev Branch to be setup just prior to the V2 release.

**Comment by RWOverdijk** [comment]
@wshafer 👍
