### ISSUE TITLE
unable to load AssetManager

### ISSUE THREAD

**Issue by wiryonolau** [RWOverdijk/AssetManager#212]
I got this error, from latest skeleton framework then adding assetmanager. I choose minimal install

Uncaught exception 'Zend\\ServiceManager\\Exception\\ServiceNotFoundException' with message 'Unable to resolve service "AssetManager\\Service\\AssetManager" to a factory

    "php": "^5.6 || ^7.0",
    "zendframework/zend-component-installer": "^1.0 || ^0.7 || ^1.0.0-dev@dev",
    "zendframework/zend-mvc": "^3.0.1",
    "zfcampus/zf-development-mode": "^3.0",
    "rwoverdijk/assetmanager": "^1.7",
    "zendframework/zend-mvc-console": "^1.1",
    "zendframework/zend-filter": "^2.7"

I still using php5.6 does this cause it, modules.config.php only consist of 

    'Zend\Router',
    'Zend\Validator',
    'AssetManager',
    'Application',

**Comment by RWOverdijk** [comment]
This might be fixed with the last release. Could you verify?
