### ISSUE TITLE
packagist versions not auto updated 

### ISSUE THREAD

**Issue by svycka** [RWOverdijk/AssetManager#225]
![image](https://user-images.githubusercontent.com/1270782/102899319-69aff880-4473-11eb-9595-4489c93890d0.png)
missing new 3.0 version also is there a changelog? at least breaking changes if any?

**Comment by RWOverdijk** [comment]
I've resynced with packagist.

Regarding the changelog, we don't have one currently. Maybe if we ask @thomasvargiu nicely he'll be willing to say what changed.

For the time being, [this PR](https://github.com/RWOverdijk/AssetManager/pull/221) is the reason for the major bump.

**Comment by thomasvargiu** [comment]
I'll try, but the biggest BC break is indirectly the migration to the `assetic-php/assetic` library. You can read the release notes here: https://github.com/assetic-php/assetic/releases/tag/v2.0.0

**Comment by thomasvargiu** [comment]
@RWOverdijk I updated the [PR description](https://github.com/RWOverdijk/AssetManager/pull/221) with the changelog, you can use it for the release notes in the github release page. Feel free to change it, and fix my english mistakes :)
