### ISSUE TITLE
Applying filters

### ISSUE THREAD

**Issue by DmitryVarennikov** [RWOverdijk/AssetManager#37]
When I add to config filters like that 

```
'filters' => array(
    'css/application/test.css' => array(
        array(
            'filter' => 'JSMinFilter', // 'CssMinFilter', 
        ),
    ),
),
```

**kriswallsmith/assetic** package throws exceptions like this 

```
Fatal error: Class 'JSMin' not found in /var/www/zend-skeleton/vendor/kriswallsmith/assetic/src/Assetic/Filter/JSMinFilter.php on line 32
```

I know ithis isse is related more to **kriswallsmith/assetic** package then yours but probably I'm doing smth wrong?!

**Comment by jarrettj** [comment]
Thanks @RWOverdijk. For anyone using composer, linkorb/jsmin-php worked for me. https://packagist.org/packages/linkorb/jsmin-php.

**Comment by Committing** [comment]
Cheers @jarrettj - Worked for me. The jsmin-php linked above is dead now.

**Comment by jarrettj** [comment]
@Committing Thanks man, I changed link to search in packagist instead :)
